<a href="https://colab.research.google.com/github/kaosarul/Deep_Learning_Pytorch/blob/main/intro_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import torch



In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.37227503, 0.89125252, 0.41307085, 0.72109786],
       [0.78432459, 0.86171827, 0.43285595, 0.73643113],
       [0.29376339, 0.57778524, 0.51564337, 0.06546183]])

In [7]:
np.dtype

numpy.dtype

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8491, -0.0920,  0.4506,  0.1508],
        [ 0.3076,  0.0975,  1.3063,  1.1027],
        [ 1.0528,  0.7608,  0.2128, -0.8006]])

In [9]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.3452, -0.9923, -0.3263,  0.1007],
         [ 0.0955,  0.3476,  0.7393, -0.9165],
         [ 0.5123, -1.0181, -0.6585,  1.8618]],

        [[-1.9321,  0.8165, -0.1168,  0.5769],
         [-0.2417,  0.0894,  0.7632,  0.5973],
         [ 2.4982, -0.3449, -1.0751,  0.2208]]])